site_name: OSG Production
site_url: https://osg-htc.org/production/
repo_url: https://github.com/osg-htc/production/
google_analytics: ['UA-69012-29', 'opensciencegrid.github.io']
theme:
  name: material
  custom_dir: osgthedocs
  favicon: 'img/favicon.ico'

extra_css:
  - css/extra.css

nav:
- Home: 'index.md'

markdown_extensions:
  - admonition
  - codehilite
#- toc(permalink=true)
  - toc

