site_name: OSG Documentation
site_url: https://opensciencegrid.github.io/production
repo_url: https://github.com/opensciencegrid/production
theme: readthedocs

extra_css:
  - css/extra.css

pages:
- Home: 'index.md'
- WeeklyMinutes: 'WeeklyMinutes.md'
  - Minutes:
    - 14 February 2017: 'WeeklyMinutes/Minutes/14Feb2017.md'
- WeeklyTemplate: 'WeeklyTemplate.md'

markdown_extensions:
  - admonition
  - osg_markdown.colors

