site_name: OSG Documentation
site_url: https://opensciencegrid.github.io/production
repo_url: https://github.com/opensciencegrid/production
theme: readthedocs

extra_css:
  - css/extra.css

pages:
- Home: 'index.md'
- Weekly Minutes:
  - '28 Februray 2017': 'WeeklyMinutes/28Feb2017.md'
  - '21 February 2017': 'WeeklyMinutes/21Feb2017.md'
  - '14 February 2017': 'WeeklyMinutes/14Feb2017.md'
  - '7 February 2017': 'WeeklyMinutes/14Feb2017.md'
- Weekly Template: 
  - 'Template': 'WeeklyTemplate.md'

markdown_extensions:
  - admonition
  - osg_markdown.colors

