site_name: OSG Production
site_url: https://opensciencegrid.org/production/
repo_url: https://github.com/opensciencegrid/production/
theme: 
  name: readthedocs

google_analytics: ['UA-69012-29', 'opensciencegrid.github.io']
theme:
  name: material
  favicon: 'img/favicon.ico'

extra_css:
  - css/extra.css

pages:
- Home: 'index.md'
- Weekly Minutes:
  - '29 May 2018': 'WeeklyMinutes/29May2018.md'
  - '15 May 2018': 'WeeklyMinutes/15May2018.md'
  - '8 May 2018': 'WeeklyMinutes/08May2018.md'
  - '1 May 2018': 'WeeklyMinutes/01May2018.md'
  - '24 April 2018': 'WeeklyMinutes/24April2018.md'
  - '17 April 2018': 'WeeklyMinutes/17April2018.md'
  - '10 April 2018': 'WeeklyMinutes/10April2018.md'
  - '3 April 2018': 'WeeklyMinutes/03April2018.md'
  - '27 March 2018': 'WeeklyMinutes/27March2018.md'
  - '13 March 2018': 'WeeklyMinutes/13March2018.md'
  - '6 March 2018': 'WeeklyMinutes/06March2018.md'
  - '27 February 2018': 'WeeklyMinutes/27February2018.md'
  - '20 February 2018': 'WeeklyMinutes/20February2018.md'
  - '13 February 2018': 'WeeklyMinutes/13February2018.md'
  - '6 February 2018': 'WeeklyMinutes/06February2018.md'
  - '30 January 2018': 'WeeklyMinutes/30January2018.md'
  - '23 January 2018': 'WeeklyMinutes/23January2018.md'
  - '16 January 2018': 'WeeklyMinutes/16January2018.md'
  - '9 January 2018': 'WeeklyMinutes/09January2018.md'

markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
  - osg_markdown.colors

