site_name: OSG Production
site_url: https://opensciencegrid.org/production/
repo_url: https://github.com/opensciencegrid/production/
google_analytics: ['UA-69012-29', 'opensciencegrid.github.io']
theme:
  name: material
  custom_dir: osgthedocs
  favicon: 'img/favicon.ico'

extra_css:
  - css/extra.css

pages:
- Home: 'index.md'
- Weekly Minutes:
  - 'May 29, 2018': 'WeeklyMinutes/2018/29May2018.md'
  - 'May 15, 2018': 'WeeklyMinutes/2018/15May2018.md'
  - 'May 8, 2018': 'WeeklyMinutes/2018/08May2018.md'
  - 'May 1, 2018': 'WeeklyMinutes/2018/01May2018.md'
  - 'April 24, 2018': 'WeeklyMinutes/2018/24April2018.md'
  - 'April 17, 2018': 'WeeklyMinutes/2018/17April2018.md'
  - 'April 10, 2018': 'WeeklyMinutes/2018/10April2018.md'
  - 'April 3, 2018': 'WeeklyMinutes/2018/03April2018.md'
  - 'March 27, 2018': 'WeeklyMinutes/2018/27March2018.md'
  - 'March 13, 2018': 'WeeklyMinutes/2018/13March2018.md'
  - 'March 6, 2018': 'WeeklyMinutes/2018/06March2018.md'
  - 'February 27, 2018': 'WeeklyMinutes/2018/27February2018.md'
  - 'February 20, 2018': 'WeeklyMinutes/2018/20February2018.md'
  - 'February 13, 2018': 'WeeklyMinutes/2018/13February2018.md'
  - 'February 6, 2018': 'WeeklyMinutes/2018/06February2018.md'
  - 'January 30, 2018': 'WeeklyMinutes/2018/30January2018.md'
  - 'January 23, 2018': 'WeeklyMinutes/2018/23January2018.md'
  - 'January 16, 2018': 'WeeklyMinutes/2018/16January2018.md'
  - 'January 9, 2018': 'WeeklyMinutes/2018/09January2018.md'

markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
  - osg_markdown.colors

